import crafttweaker.item.IItemDefinition;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import crafttweaker.oredict.IOreDict;
import crafttweaker.oredict.IOreDictEntry;

<gregtech:meta_item_2:32454>.displayName="Silver Coated Glass Tube";
<ic2:crop_stick>.displayName="Crop Stick";
<gregtech:meta_item_1:32725>.displayName="Quantum Star";
<gregtech:meta_item_1:32724>.displayName="Quantum Eye";
<pneumaticcraft:turbine_blade>.displayName="Metastable Oganesson Plated Naquadah Alloy Turbine Blade";
<ic2:glass>.displayName="Soularium Reinforced Glass";
<forestry:apatite>.displayName="Apatite Gemstone";
<forestry:ash>.displayName="Ash Nanoparticles";
<emt:materials_thaumiumplate>.displayName="Thaumium Reinforced Plate";





<exoplanets:metalore:9>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:8>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:7>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:6>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:5>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:4>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:3>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:2>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore:1>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:metalore>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:9>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:8>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:7>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:6>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:5>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:4>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:3>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:2>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore:1>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<exoplanets:trap1eore>.addTooltip(format.red("Useless, only inside the game because the mod is bugged]"));
<appliedenergistics2:controller>.addTooltip(format.red("Requires Research"));
<modularmachinery:machine_projector>.addTooltip(format.red("Requires Research"));
<avaritia:resource:4>.addTooltip(format.green("True Neutronium"));
<liquid:pvtchs>.addTooltip(format.red("made in cells"));
<liquid:obisdianinfuseddraconiummixture>.addTooltip(format.red("made in cells"));
<liquid:draconiumrichsolution>.addTooltip(format.red("made in cells"));
<contenttweaker:lapotrondust>.addTooltip(format.red("WIP"));
<contenttweaker:rawlapotron>.addTooltip(format.red("WIP"));
<contenttweaker:quantumcontrolcomputermk1>.addTooltip(format.red("WIP"));
<contenttweaker:quantumcontrolcomputermk2>.addTooltip(format.red("WIP"));
<contenttweaker:quantumcontrolcomputermk3>.addTooltip(format.red("WIP"));
<contenttweaker:stablestar>.addTooltip(format.red("WIP"));
<contenttweaker:spacetimecontainingcomputationalunit>.addTooltip(format.red("WIP"));
<liquid:extradistilledwater>.addTooltip(format.red("WIP"));
<contenttweaker:purified1thorium>.addTooltip(format.red("WIP"));
<contenttweaker:purified2thorium>.addTooltip(format.red("WIP"));
<contenttweaker:purified3thorium>.addTooltip(format.red("WIP"));
<contenttweaker:purified4thorium>.addTooltip(format.red("WIP"));
<gregtech:meta_item_1:10517>.addTooltip(format.red("WIP"));
<contenttweaker:elementdr>.addTooltip(format.red("WIP"));
<contenttweaker:draconiumfragment>.addTooltip(format.red("WIP"));
<contenttweaker:heavydutyalloyt6>.addTooltip(format.red("WIP"));
<contenttweaker:elementds>.addTooltip(format.red("WIP"));
<contenttweaker:selementts>.addTooltip(format.red("WIP"));
<contenttweaker:elementfm>.addTooltip(format.red("WIP"));
<contenttweaker:elementlu>.addTooltip(format.red("WIP"));
<contenttweaker:elementti>.addTooltip(format.red("WIP"));
<contenttweaker:elementtr>.addTooltip(format.red("WIP"));
<contenttweaker:selementp>.addTooltip(format.red("WIP"));
<contenttweaker:elementw>.addTooltip(format.red("WIP"));






<ore:dustSodium>.remove(<qmd:dust:11>);
<ore:dustBismuth>.remove(<nuclearcraft:fission_dust>);
<ore:ingotAluminum>.remove(<thermalfoundation:material:132>);
<ore:dustZinc>.remove(<qmd:dust:7>);
<ore:dustTin>.remove(<nuclearcraft:dust:1>);
<ore:dustCalcium>.remove(<qmd:dust:13>);
<ore:dustMagnesium>.remove(<nuclearcraft:dust:7>);
<ore:dustManganese>.remove(<nuclearcraft:dust:11>);
<ore:ingotUranium>.remove(<ic2:ingot:8>);
<ore:ingotUranium>.remove(<reactor_stuff:uranium_ingot>);
<ore:dustAluminium>.remove(<nuclearcraft:dust:12>);
<ore:dustAluminum>.remove(<nuclearcraft:dust:12>);
<ore:dustDiamond>.remove(<nuclearcraft:gem_dust>);
<ore:dustNickel>.remove(<qmd:dust:5>);
<ore:dustMolybdenum>.remove(<nuclearcraft:fission_dust:6>);
<ore:dustCobalt>.remove(<qmd:dust:4>);
<ore:ingotCopper>.remove(<nuclearcraft:ingot>);
<ore:ingotSilver>.remove(<nuclearcraft:ingot:13>);
<ore:ingotAluminium>.remove(<nuclearcraft:ingot:12>);
<ore:ingotAluminum>.remove(<nuclearcraft:ingot:12>);
<ore:ingotManganese>.remove(<nuclearcraft:ingot:11>);
<ore:ingotZirconium>.remove(<nuclearcraft:ingot:10>);
<ore:ingotMagnesium>.remove(<nuclearcraft:ingot:7>);
<ore:ingotLithium>.remove(<nuclearcraft:ingot:6>);
<ore:ingotBoron>.remove(<nuclearcraft:ingot:5>);
<ore:ingotUranium>.remove(<nuclearcraft:ingot:4>);
<ore:ingotThorium>.remove(<nuclearcraft:ingot:3>);
<ore:ingotLead>.remove(<nuclearcraft:ingot:2>);
<ore:ingotTin>.remove(<nuclearcraft:ingot:1>);
<ore:ingotBronze>.remove(<nuclearcraft:alloy>);
<ore:dustSilver>.remove(<nuclearcraft:dust:13>);
<ore:dustCopper>.remove(<nuclearcraft:dust>);
<ore:ingotNichrome>.remove(<qmd:ingot_alloy:5>);
<ore:ingotNiobiumTitanium>.remove(<qmd:ingot_alloy:3>);
<ore:ingotNeodymium>.remove(<qmd:ingot2:1>);
<ore:ingotYttrium>.remove(<qmd:ingot2>);
<ore:ingotStrontium>.remove(<qmd:ingot:14>);
<ore:ingotPotassium>.remove(<qmd:ingot:12>);
<ore:ingotPlatinum>.remove(<qmd:ingot:10>);
<ore:ingotSodium>.remove(<qmd:ingot:11>);
<ore:ingotIridium>.remove(<qmd:ingot:9>);
<ore:ingotOsmium>.remove(<qmd:ingot:8>);
<ore:ingotZinc>.remove(<qmd:ingot:7>);
<ore:ingotHafnium>.remove(<qmd:ingot:6>);
<ore:ingotNickel>.remove(<qmd:ingot:5>);
<ore:ingotCobalt>.remove(<qmd:ingot:4>);
<ore:ingotTitanium>.remove(<qmd:ingot:3>);
<ore:ingotChromium>.remove(<qmd:ingot:2>);
<ore:ingotNiobium>.remove(<qmd:ingot:1>);
<ore:ingotCalcium>.remove(<qmd:ingot:13>);
<ore:ingotTungsten>.remove(<qmd:ingot>);
<ore:dustPlatinum>.remove(<qmd:dust:10>);
<ore:dustYtterbium>.remove(<qmd:dust2:6>);
<ore:dustPolonium>.remove(<nuclearcraft:fission_dust:2>);
<ore:dustRadium>.remove(<nuclearcraft:fission_dust:1>);
<ore:ingotBeryllium>.remove(<nuclearcraft:ingot:9>);
<ore:ingotStainlessSteel>.remove(<qmd:ingot_alloy:2>);
<ore:dustTungsten>.remove(<qmd:dust>);
<ore:dustSodiumFluoride>.remove(<nuclearcraft:compound:3>);
<ore:dustSodiumHydroxide>.remove(<nuclearcraft:compound:5>);
<ore:dustLead>.remove(<nuclearcraft:dust:2>);
<ore:dustSamarium>.remove(<qmd:dust2:3>);
<ore:ingotTungstenCarbide>.remove(<qmd:ingot_alloy>);
<ore:ingotSteel>.remove(<nuclearcraft:alloy:5>);
<ore:ingotOsmiridium>.remove(<qmd:ingot_alloy:4>);
<ore:dustZirconium>.remove(<nuclearcraft:dust:10>);
<ore:dustFluorite>.remove(<nuclearcraft:gem_dust:5>);
<ore:dustIodine>.remove(<qmd:dust2:2>);
<ore:dustSulfur>.remove(<nuclearcraft:gem_dust:6>);
<ore:dustBoron>.remove(<nuclearcraft:dust:5>);
<ore:dustArsenic>.remove(<nuclearcraft:gem_dust:10>);
<ore:dustBeryllium>.remove(<nuclearcraft:dust:9>);
<ore:oreUranium>.remove(<nuclearcraft:ore:4>);
<ore:circuitElite>.remove(<gregtech:meta_item_2:32496>);
<ore:ingotGraphite>.remove(<nuclearcraft:ingot:8>);
<ore:dustGraphite>.remove(<nuclearcraft:dust:8>);
<ore:blockTin>.remove(<nuclearcraft:ingot_block:1>);
<ore:blockLead>.remove(<nuclearcraft:ingot_block:2>);
<ore:blockThorium>.remove(<nuclearcraft:ingot_block:3>);
<ore:blockUranium>.remove(<nuclearcraft:ingot_block:4>);
<ore:blockBeryllium>.remove(<nuclearcraft:ingot_block:9>);
<ore:blockFissionModerator>.remove(<nuclearcraft:ingot_block:9>);
<ore:blockFissionModerator>.remove(<nuclearcraft:ingot_block:8>);
<ore:blockGraphite>.remove(<nuclearcraft:ingot_block:8>);
<ore:blockMagnesium>.remove(<nuclearcraft:ingot_block:7>);
<ore:blockLithium>.remove(<nuclearcraft:ingot_block:6>);
<ore:blockBoron>.remove(<nuclearcraft:ingot_block:5>);
<ore:blockSilver>.remove(<nuclearcraft:ingot_block:13>);
<ore:blockAluminium>.remove(<nuclearcraft:ingot_block:12>);
<ore:blockAluminum>.remove(<nuclearcraft:ingot_block:12>);
<ore:blockZirconium>.remove(<nuclearcraft:ingot_block:10>);
<ore:blockManganese>.remove(<nuclearcraft:ingot_block:11>);
<ore:blockCopper>.remove(<nuclearcraft:ingot_block>);
<ore:oreMagnesium>.remove(<nuclearcraft:ore:7>);
<ore:oreLithium>.remove(<nuclearcraft:ore:6>);
<ore:oreBoron>.remove(<nuclearcraft:ore:5>);
<ore:oreUranium>.remove(<reactor_stuff:ore_uranium>);
<ore:oreThorium>.remove(<nuclearcraft:ore:3>);
<ore:oreLead>.remove(<nuclearcraft:ore:2>);
<ore:oreTin>.remove(<nuclearcraft:ore:1>);
<ore:oreCopper>.remove(<nuclearcraft:ore>);
<ore:nuggetCosmicNeutronium>.remove(<avaritia:resource:3>);
<ore:gearDiamond>.remove(<buildcraftcore:gear_diamond>);
<ore:gearGold>.remove(<buildcraftcore:gear_gold>);
<ore:gearIron>.remove(<buildcraftcore:gear_iron>);
<ore:gearStone>.remove(<buildcraftcore:gear_stone>);
<ore:gearWood>.remove(<buildcraftcore:gear_wood>);
<ore:blockCharcoal>.remove(<zettaindustries:charcoalblock>);
<ore:blockSulfur>.remove(<zettaindustries:sulfurblock>);
<ore:blockGraphite>.remove(<zettaindustries:blockgraphite>);
<ore:nuggetStellaralloy>.add(<enderio:item_alloy_endergy_nugget:3>);
<ore:nuggetStellaralloy>.remove(<gregtech:meta_item_1:9569>);
<ore:ingotStellaralloy>.add(<enderio:item_alloy_endergy_ingot:3>);
<ore:ingotStellaralloy>.remove(<gregtech:meta_item_1:10569>);
<ore:dustThorium>.remove(<reactor_stuff:thorium_dust>);
<ore:ingotThorium>.remove(<reactor_stuff:thorium_ingot>);
<ore:dustEinsteinium>.remove(<reactor_stuff:terminium_dust>);
<ore:ingotEinsteinium>.remove(<reactor_stuff:terminium_ingot>);
<ore:blockGlass>.remove(<galaxyspace:futureglass>);
<ore:plateThaumium>.remove(<emt:materials_thaumiumplate>);
<ore:nuggetIridium>.remove(<ic2:misc_resource:2>);
<ore:dustAsh>.remove(<forestry:ash>);
<ore:gemApatite>.remove(<forestry:apatite>);
<ore:ingotLead>.remove(<ic2:ingot:3>);
<ore:ingotSignalum>.remove(<gregtech:meta_item_1:10539>);
<ore:nuggetSignalum>.remove(<gregtech:meta_item_1:9539>);
<ore:dustSignalum>.remove(<gregtech:meta_item_1:2539>);
<ore:dustRegularSignalum>.remove(<gregtech:meta_item_1:2539>);
<ore:gemRuby>.remove(<projectred-core:resource_item:200>);
<ore:gemSapphire>.remove(<projectred-core:resource_item:201>);
<ore:blockNetherStar>.remove(<extendedcrafting:storage:2>);
<ore:blockNetherStar>.remove(<overloaded:nether_star_block>);
<ore:ingotSilver>.remove(<projectred-core:resource_item:102>);
<ore:ingotCopper>.remove(<projectred-core:resource_item:100>);
<ore:ingotTin>.remove(<projectred-core:resource_item:101>);
<ore:ingotRedAlloy>.remove(<projectred-core:resource_item:103>);
<ore:nuggetCopper>.remove(<thaumcraft:nugget:1>);
<ore:ingotZyptorium>.add(<moreplanets:zyptorium_ingot>);
<ore:blockZyptorium>.add(<moreplanets:zyptorium_block>);
<ore:dustAlumina>.remove(<gtadditions:ga_dust:44>);
<ore:oreMithril>.remove(<thermalfoundation:ore:8>);
<ore:manainfusedore>.add(<thermalfoundation:ore:8>);
<ore:dustTitanium>.remove(<galacticraftplanets:item_basic_asteroids:9>);
<ore:dustTinyTitanium>.remove(<galacticraftcore:ic2compat:7>);
<ore:nuggetUltimate>.remove(<gregtech:meta_item_1:9523>);
<ore:blockUltimate>.remove(<gregtech:meta_block_compressed_32:11>);
<ore:ingotUltimate>.remove(<gregtech:meta_item_1:10523>);
<ore:ingotSoularium>.remove(<enderio:item_alloy_ingot:7>);
<ore:dustSoularium>.remove(<enderio:item_material:74>);
<ore:blockApatite>.remove(<forestry:resource_storage>);
<ore:oreApatite>.remove(<forestry:resources>);
<ore:nuggetIron>.remove(<thaumcraft:nugget>);
<ore:crystaltinebaseingot>.add(<contenttweaker:crystaltinebaseingot>);
<ore:circuitGood>.remove(<gtadditions:ga_meta_item:32222>);
<ore:circuitElite>.remove(<gtadditions:ga_meta_item:32225>);
<ore:circuitUev>.remove(<gtadditions:ga_meta_item:32232>);
<ore:circuitUltimate>.remove(<gtadditions:ga_meta_item:32227>);
<ore:circuitSuperconductor>.remove(<gtadditions:ga_meta_item:32228>);
<ore:circuitInfinite>.remove(<gtadditions:ga_meta_item:32229>);
<ore:circuitBasic>.remove(<gtadditions:ga_meta_item:32221>);
<ore:circuitAdvanced>.remove(<gtadditions:ga_meta_item:32223>);
<ore:circuitExtreme>.remove(<gtadditions:ga_meta_item:32224>);
<ore:circuitMaster>.remove(<gtadditions:ga_meta_item:32226>);
<ore:circuitAdvanced>.remove(<ic2:crafting:2>);
<ore:circuitBasic>.remove(<ic2:crafting:1>);
<ore:plateIron>.remove(<thaumcraft:plate:1>);
<ore:plateBrass>.remove(<thaumcraft:plate>);
<ore:ingotCosmicNeutronium>.remove(<avaritia:resource:4>);
<ore:denseice>.add(<galacticraftplanets:dense_ice>);
<ore:titaniumice>.add(<contenttweaker:titaniumcontainingice>);
<ore:plateBronze>.remove(<galacticraftcore:basic_item:10>);
<ore:plateCopper>.remove(<galacticraftcore:basic_item:6>);
<ore:plateTin>.remove(<galacticraftcore:basic_item:7>);
<ore:plateAluminum>.remove(<galacticraftcore:basic_item:8>);
<ore:plateSteel>.remove(<galacticraftcore:basic_item:9>);
<ore:plateIron>.remove(<galacticraftcore:basic_item:11>);
<ore:plateDesh>.remove(<galacticraftplanets:item_basic_mars:5>);
<ore:plateTitanium>.remove(<galacticraftplanets:item_basic_asteroids:6>);
<ore:ingotBrass>.remove(<thaumcraft:ingot:2>);
<ore:blockBrass>.remove(<thaumcraft:metal_brass>);
<ore:nuggetBrass>.remove(<thaumcraft:nugget:8>);
<ore:dustSulfur>.remove(<thermalfoundation:material:771>);
<ore:craftingToolWireCutter>.remove(<ic2:cutter>);
<ore:nuggetLead>.remove(<thaumcraft:nugget:4>);
<ore:plateMagnesium>.remove(<galaxyspace:compressed_plates:2>);
<ore:plateCopper>.remove(<ic2:plate:1>);
<ore:itemSawdust>.remove(<thermalfoundation:material:800>);
<ore:dustWood>.remove(<thermalfoundation:material:800>);
<ore:dustEnderEye>.remove(<ic2:dust:32>);
<ore:blockInfinity>.remove(<gregtech:meta_block_compressed_35:1>);
<ore:ingotInfinity>.remove(<gregtech:meta_item_1:10561>);
<ore:plateNickel>.remove(<galaxyspace:compressed_plates:3>);
<ore:ingotLumium>.remove(<gregtech:meta_item_1:10532>);
<ore:blockSilicon>.remove(<galacticraftcore:basic_block_core:13>);
<ore:itemSilicon>.remove(<galacticraftcore:basic_item:2>);
<ore:rawSilicon>.remove(<galacticraftcore:basic_item:2>);
<ore:rawblockSilicon>.remove(<galacticraftcore:basic_block_core:13>);
<ore:voodooPoppetProtectionLightning>.remove(<minecraft:stick>);
<ore:dustYttrium>.remove(<qmd:dust2>);
<ore:dustPotassium>.remove(<qmd:dust:12>);
<ore:dustLithium>.remove(<nuclearcraft:dust:6>);
<ore:dustPotatoAlloy>.add(<contenttweaker:potato_alloy_dust>);
<ore:ingotPotatoAlloy>.add(<thaumicpotatoes:potatoalloy>);


